; logger.conf -- log to stdout (docker logs) AND to /var/log/asterisk/full
[general]
dateformat = %F %T

[logfiles]
console  => notice,warning,error,verbose(3)
messages => notice,warning,error
full     => notice,warning,error,debug,verbose,dtmf
